/* Licensed under the Apache License, Version 2.0. */
package com.nereusstream.storage.object.nwg1;

/** Closed NWG1 v1 rejection vocabulary. */
public enum Nwg1RejectionV1 {
    NON_CANONICAL_ENCODING,
    TRUNCATED_INPUT,
    TRAILING_BYTES,
    UNSUPPORTED_VERSION,
    UNKNOWN_CODE,
    REQUIRED_ZERO_NONZERO,
    VALUE_DOMAIN_VIOLATION,
    DECLARED_LENGTH_MISMATCH,
    COUNT_MISMATCH,
    LIMIT_EXCEEDED,
    ARITHMETIC_OVERFLOW,
    CHECKSUM_MISMATCH,
    DIGEST_MISMATCH,
    AUTHORITY_MISMATCH,
    KEY_UNWRAP_FAILED,
    AEAD_AUTHENTICATION_FAILED,
    CANONICAL_ORDER_VIOLATION,
    DUPLICATE_IDENTITY,
    REFERENCE_OUT_OF_RANGE,
    RANGE_GAP,
    RANGE_OVERLAP,
    COVERAGE_MISMATCH,
    CODEC_CONTRACT_VIOLATION,
    NATIVE_FRAMING_INVALID,
    NATIVE_CHECKSUM_MISMATCH
}
