{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nereusstream",
    "module": "nereus-storage-bookkeeper",
    "version": "0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nereusstream",
          "module": "nereus-storage-api",
          "version": {
            "requires": "0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c"
          }
        }
      ],
      "files": [
        {
          "name": "nereus-storage-bookkeeper-0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c.jar",
          "url": "nereus-storage-bookkeeper-0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.bookkeeper",
          "module": "bookkeeper-server",
          "version": {
            "requires": "4.18.0"
          }
        },
        {
          "group": "com.nereusstream",
          "module": "nereus-storage-api",
          "version": {
            "requires": "0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c"
          }
        }
      ],
      "files": [
        {
          "name": "nereus-storage-bookkeeper-0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c.jar",
          "url": "nereus-storage-bookkeeper-0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nereus-storage-bookkeeper-0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c-sources.jar",
          "url": "nereus-storage-bookkeeper-0.2.0-m2.cf465a637b960642b08287c5178ad45f2c0a240c-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
