#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_root="$repo_root/nereus-domain/src/test/java/com/nereusstream/domain/registry"
result_file="$repo_root/nereus-domain/build/test-results/test/TEST-com.nereusstream.domain.registry.RegistryCapacityEvidenceTest.xml"
generated_root="$repo_root/nereus-domain/build/reports/v2-m1-registry-capacity"
generated_json="$generated_root/registry-capacity.json"
generated_markdown="$generated_root/README.md"
evidence_root="$repo_root/docs/v2/evidence/v2-m0/m1.1c-r0"
committed_json="$evidence_root/registry-capacity.json"
committed_markdown="$evidence_root/README.md"
source_commit_file="$evidence_root/source-commit.txt"
scenarios="$repo_root/docs/v2/v2-scenarios.json"

fail() {
    echo "V2 M1.1c-R0 Registry capacity check: $*" >&2
    exit 1
}

for required in \
    "$test_root/RegistryCapacityHarness.java" \
    "$test_root/RegistryCapacityEvidenceTest.java" \
    "$result_file" \
    "$generated_json" \
    "$generated_markdown" \
    "$committed_json" \
    "$committed_markdown" \
    "$source_commit_file"; do
    [[ -f "$required" ]] || fail "missing ${required#"$repo_root/"}"
done

if rg -n 'RegistryCapacityHarness|RegistryCapacityEvidenceTest|REGISTRY_CAPACITY_READINESS_ONLY' \
    "$repo_root/nereus-domain/src/main" \
    "$repo_root/nereus-metadata-spi/src/main" \
    "$repo_root/nereus-metadata-oxia/src/main"; then
    fail "test/evidence-only Registry capacity symbols leaked into production source"
fi

if rg -n 'org\.testcontainers|Docker|docker compose|docker-compose' "$test_root" --glob '*.java'; then
    fail "Registry capacity readiness evidence depends on Docker/Testcontainers"
fi

if rg -n 'productionRegistryAuthorityImplemented"[[:space:]]*:[[:space:]]*true|registryConformance"[[:space:]]*:[[:space:]]*true|allocatorModeSelected"[[:space:]]*:[[:space:]]*true|runtimeActivated"[[:space:]]*:[[:space:]]*true|scenarioPromotion"[[:space:]]*:[[:space:]]*true' \
    "$committed_json" "$generated_json"; then
    fail "Registry capacity evidence claims production authority, conformance, allocator selection, runtime, or promotion"
fi

rg -Fq 'new UnavailableRegistryAuthorityCodec()' \
    "$repo_root/nereus-metadata-oxia/src/main/java/com/nereusstream/metadata/oxia/v2/codec/OxiaV2CodecSet.java" \
    || fail "production Registry codec no longer remains unavailable"
rg -Fq 'void registryCodecGapFailsBeforeIo()' \
    "$repo_root/nereus-metadata-oxia/src/test/java/com/nereusstream/metadata/oxia/v2/capability/ProductionCodecFailClosedTest.java" \
    || fail "production Registry codec fail-closed test is missing"

python3 - \
    "$result_file" \
    "$generated_json" \
    "$committed_json" \
    "$generated_markdown" \
    "$committed_markdown" \
    "$source_commit_file" \
    "$scenarios" <<'PY'
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

(
    result_path,
    generated_json_path,
    committed_json_path,
    generated_markdown_path,
    committed_markdown_path,
    source_commit_path,
    scenarios_path,
) = map(pathlib.Path, sys.argv[1:])

suite = ET.parse(result_path).getroot()
totals = {name: int(suite.attrib.get(name, "0")) for name in ("tests", "failures", "errors", "skipped")}
expected_totals = {"tests": 18, "failures": 0, "errors": 0, "skipped": 0}
if totals != expected_totals:
    raise SystemExit(
        f"V2 M1.1c-R0 Registry capacity check: expected focused totals {expected_totals}, found {totals}"
    )

generated_json_bytes = generated_json_path.read_bytes()
committed_json_bytes = committed_json_path.read_bytes()
if generated_json_bytes != committed_json_bytes:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: committed JSON differs from generated bytes")

generated_markdown_bytes = generated_markdown_path.read_bytes()
committed_markdown_bytes = committed_markdown_path.read_bytes()
if generated_markdown_bytes != committed_markdown_bytes:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: committed Markdown differs from generated bytes")

evidence = json.loads(committed_json_bytes)
expected_boundary = {
    "schemaVersion": 1,
    "sourceTupleId": "v2-m0",
    "result": "REGISTRY_CAPACITY_READINESS_ONLY",
    "promotionEligible": False,
    "registryConformance": False,
    "productionRegistryAuthorityImplemented": False,
    "allocatorModeSelected": False,
    "runtimeActivated": False,
    "scenarioPromotion": False,
}
for key, expected in expected_boundary.items():
    if evidence.get(key) != expected:
        raise SystemExit(f"V2 M1.1c-R0 Registry capacity check: invalid evidence field {key}")

expected_inputs = {
    "writerKinds": 2,
    "writerRowBytes": 120,
    "fixedHeaderBytes": 184,
    "maxRegistryEnvelopeBytes": 65536,
    "maxAssignmentsEver": 256,
    "maxAssignmentRowBytes": 192,
    "sliceExponent": 40,
    "oxiaExpectedVersionBytes": 8,
}
if evidence.get("fixedInputs") != expected_inputs:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: fixed inputs drifted")

expected_breakdown = {
    "fixedHeaderBytes": 184,
    "writerBytes": 1680,
    "assignmentBytes": 49152,
    "canonicalRegistryBytes": 51016,
    "inheritedEnvelopeBytes": 65536,
    "reservedMarginBytes": 14520,
    "oxiaValueBytes": 51016,
    "oxiaCasCandidateValueBytes": 51016,
    "oxiaCasExpectedVersionBytes": 8,
    "oxiaValuePlusVersionOperandsBytes": 51024,
    "keyAndRpcFramingIncluded": False,
}
if evidence.get("maximumBreakdown") != expected_breakdown:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: canonical/Oxia breakdown drifted")

if 184 + 14 * 120 + 256 * 192 != 51016 or 65536 - 51016 != 14520:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: checked formula no longer reproduces the boundary")

expected_scenarios = [
    ("steady-native-bookkeeper", 1, 49456),
    ("steady-nereus-virtual-ledger", 1, 49456),
    ("combined-steady", 2, 49576),
    ("old-new-binary-coexistence", 4, 49816),
    ("binary-credential-two-by-two", 8, 50296),
    ("rollback-fresh-generations", 10, 50536),
    ("fenced-not-cleaned-residue", 12, 50776),
    ("allocation-capable-bootstrap-admin", 14, 51016),
]
actual_scenarios = [
    (item["id"], item["writerCount"], item["registryBytesAt256Rows"])
    for item in evidence.get("scenarios", [])
]
if actual_scenarios != expected_scenarios:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: cohort scenarios drifted")

required_errors = {
    "REGISTRY_WRITER_COUNT_EXCEEDED",
    "REGISTRY_CANONICAL_BYTES_EXCEEDED",
    "REGISTRY_ASSIGNMENT_COUNT_EXCEEDED",
    "REGISTRY_ASSIGNMENT_ROW_BYTES_EXCEEDED",
    "REGISTRY_OMITTED_AUTHORIZED_WRITER",
    "REGISTRY_UNAUTHORIZED_WRITER",
    "REGISTRY_WRITER_LIFECYCLE_VIOLATION",
}
if set(evidence.get("rejectionCodes", [])) != required_errors:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: rejection taxonomy drifted")

source_commit = source_commit_path.read_text(encoding="ascii").strip()
if not re.fullmatch(r"[0-9a-f]{40}", source_commit):
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: malformed source commit")
if evidence.get("source") != {
    "nereusCommit": source_commit,
    "requiredBaselineCommit": "26728bec826ac72e5b893d4d19983d588feaca4f",
}:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: source binding drifted")
subprocess.run(["git", "cat-file", "-e", f"{source_commit}^{{commit}}"], check=True)
subprocess.run(
    [
        "git",
        "merge-base",
        "--is-ancestor",
        "26728bec826ac72e5b893d4d19983d588feaca4f",
        source_commit,
    ],
    check=True,
)

json_sha = hashlib.sha256(committed_json_bytes).hexdigest()
markdown = committed_markdown_bytes.decode("utf-8")
if source_commit not in markdown or json_sha not in markdown:
    raise SystemExit("V2 M1.1c-R0 Registry capacity check: Markdown source or JSON digest binding drifted")

scenario_data = json.loads(scenarios_path.read_text())
statuses = {item["id"]: item["status"] for item in scenario_data["scenarios"]}
for ordinal in range(3, 11):
    scenario_id = f"V2-POSITION-{ordinal:03d}"
    if statuses.get(scenario_id) != "PLANNED":
        raise SystemExit(f"V2 M1.1c-R0 Registry capacity check: {scenario_id} was promoted")

print(
    "V2 M1.1c-R0 focused tests: "
    f"suites=1 tests={totals['tests']} failures=0 errors=0 skipped=0 "
    f"jsonSha256={json_sha}"
)
PY

echo "V2 M1.1c-R0 Registry capacity readiness verified; no R1 authority, real Oxia, allocator selection, scenario promotion, or M1 PASS."
