#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_root="$repo_root/nereus-domain/src/test/java/com/nereusstream/domain/receipt"
fixture="$repo_root/nereus-domain/src/test/resources/receipt/m1-current-junit-inventory.tsv"
result_file="$repo_root/build/test-results/v2-m1-receipt-caps/TEST-com.nereusstream.domain.receipt.ReceiptV1CapacityEvidenceTest.xml"
generated_root="$repo_root/nereus-domain/build/reports/v2-m1-receipt-caps"
generated_json="$generated_root/receipt-caps.json"
generated_markdown="$generated_root/README.md"
evidence_root="$repo_root/docs/v2/evidence/v2-m0/m1-2-receipt-caps"
committed_json="$evidence_root/receipt-caps.json"
committed_markdown="$evidence_root/README.md"
source_commit_file="$evidence_root/source-commit.txt"
source_locks_input_file="$evidence_root/source-locks-input.sha256"
source_locks="$repo_root/docs/v2/source-locks.json"
scenarios="$repo_root/docs/v2/v2-scenarios.json"

fail() {
    echo "V2 M1-2 receipt/parser cap check: $*" >&2
    exit 1
}

for required in \
    "$test_root/ReceiptV1CapacityModel.java" \
    "$test_root/ReceiptV1CapacitySamples.java" \
    "$test_root/ReceiptV1CapacityEvidenceTest.java" \
    "$fixture" \
    "$result_file" \
    "$generated_json" \
    "$generated_markdown" \
    "$committed_json" \
    "$committed_markdown" \
    "$source_commit_file" \
    "$source_locks_input_file" \
    "$source_locks" \
    "$scenarios"; do
    [[ -f "$required" ]] || fail "missing ${required#"$repo_root/"}"
done

if rg -n 'ReceiptV1Capacity|RECEIPT_CAPACITY_READINESS_ONLY' \
    "$repo_root/nereus-domain/src/main" \
    "$repo_root/nereus-metadata-spi/src/main" \
    "$repo_root/nereus-metadata-oxia/src/main"; then
    fail "test/evidence-only receipt-cap symbols leaked into production source"
fi

if rg -n 'org\.testcontainers|Docker|docker compose|docker-compose|OxiaClient|MetadataStore' \
    "$test_root" --glob '*.java'; then
    fail "receipt-cap readiness evidence depends on Docker, real Oxia, or runtime metadata"
fi

if rg -n '"(promotionEligible|productionReceiptParserImplemented|runtimeActivated|scenarioPromotion|m1Final)"[[:space:]]*:[[:space:]]*true|PASSED_CURRENT_SOURCE' \
    "$committed_json" "$generated_json"; then
    fail "receipt-cap readiness evidence claims production, promotion, or M1 Final authority"
fi

python3 - \
    "$result_file" \
    "$generated_json" \
    "$committed_json" \
    "$generated_markdown" \
    "$committed_markdown" \
    "$source_commit_file" \
    "$source_locks_input_file" \
    "$source_locks" \
    "$scenarios" \
    "$test_root/ReceiptV1CapacityModel.java" \
    "$test_root/ReceiptV1CapacitySamples.java" \
    "$repo_root" <<'PY'
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import xml.etree.ElementTree as ET

(
    result_path,
    generated_json_path,
    committed_json_path,
    generated_markdown_path,
    committed_markdown_path,
    source_commit_path,
    source_locks_input_path,
    source_locks_path,
    scenarios_path,
    model_path,
    samples_path,
    repo_root,
) = map(pathlib.Path, sys.argv[1:])

suite = ET.parse(result_path).getroot()
totals = {name: int(suite.attrib.get(name, "0")) for name in ("tests", "failures", "errors", "skipped")}
expected_totals = {"tests": 36, "failures": 0, "errors": 0, "skipped": 0}
if totals != expected_totals:
    raise SystemExit(
        f"V2 M1-2 receipt/parser cap check: expected focused totals {expected_totals}, found {totals}"
    )

generated_json_bytes = generated_json_path.read_bytes()
committed_json_bytes = committed_json_path.read_bytes()
if generated_json_bytes != committed_json_bytes:
    raise SystemExit("V2 M1-2 receipt/parser cap check: committed JSON differs from generated bytes")
if generated_markdown_path.read_bytes() != committed_markdown_path.read_bytes():
    raise SystemExit("V2 M1-2 receipt/parser cap check: committed Markdown differs from generated bytes")

evidence = json.loads(committed_json_bytes)
expected_boundary = {
    "schemaVersion": 1,
    "sourceTupleId": "v2-m0",
    "result": "RECEIPT_CAPACITY_READINESS_ONLY",
    "promotionEligible": False,
    "productionReceiptParserImplemented": False,
    "runtimeActivated": False,
    "scenarioPromotion": False,
    "m1Final": False,
    "sampleRootsAreTestVectors": True,
}
for key, expected in expected_boundary.items():
    if evidence.get(key) != expected:
        raise SystemExit(f"V2 M1-2 receipt/parser cap check: invalid evidence field {key}")

expected_caps = {
    "canonicalRootBytes": 65536,
    "scenariosPerReceipt": 16,
    "suitesPerScenario": 128,
    "attachmentsPerReceipt": 32,
    "singleAttachmentBytes": 262144,
    "totalAttachmentBytes": 524288,
    "relativePathBytes": 256,
    "relativePathSegments": 16,
    "sanitizedLogBytes": 65536,
}
if evidence.get("caps") != expected_caps:
    raise SystemExit("V2 M1-2 receipt/parser cap check: selected v1 cap table drifted")

observations = evidence.get("observations", {})
if observations.get("preM1_2BaselineJUnitXml") != {
    "suites": 91,
    "tests": 386,
    "bytes": 96248,
    "largestLockedExternalXmlBytes": 10058,
}:
    raise SystemExit("V2 M1-2 receipt/parser cap check: measured JUnit inventory drifted")
if observations.get("closedM1VirtualLedgerScenarioRows") != 9:
    raise SystemExit("V2 M1-2 receipt/parser cap check: accepted M1 scenario-row count drifted")
if observations.get("registryMaximumBytes") != 51016:
    raise SystemExit("V2 M1-2 receipt/parser cap check: accepted Registry maximum drifted")

maxima = observations.get("maxima", {})

def next_power_of_two(value):
    if not isinstance(value, int) or value <= 0:
        raise SystemExit("V2 M1-2 receipt/parser cap check: invalid cap derivation input")
    return 1 << (value - 1).bit_length()

derived_caps = {
    "canonicalRootBytes": next_power_of_two(4 * maxima.get("canonicalRootBytes", 0)),
    "scenariosPerReceipt": next_power_of_two((9 * 3 + 1) // 2),
    "suitesPerScenario": next_power_of_two((73 * 3 + 1) // 2),
    "attachmentsPerReceipt": next_power_of_two(5 * 4),
    "singleAttachmentBytes": next_power_of_two(2 * max(96248, 51016)),
    "totalAttachmentBytes": max(
        next_power_of_two(2 * maxima.get("kindCompleteBundleBytes", 0)),
        2 * expected_caps["singleAttachmentBytes"],
    ),
    "relativePathBytes": next_power_of_two(2 * maxima.get("relativePathBytes", 0)),
    "relativePathSegments": next_power_of_two(2 * maxima.get("relativePathSegments", 0)),
    "sanitizedLogBytes": next_power_of_two(4 * maxima.get("sanitizedLogBytes", 0)),
}
if derived_caps != expected_caps:
    raise SystemExit(
        f"V2 M1-2 receipt/parser cap check: observed maxima derive {derived_caps}, expected {expected_caps}"
    )

expected_sample_ids = [
    "fault-cut",
    "foundation",
    "maximum-failure",
    "multi-scenario-harness",
    "multi-scenario-registry",
    "multi-suite",
    "nta1",
    "o1",
    "o2",
    "registry-readiness",
    "representative-all-pass",
]
samples = observations.get("samples", [])
if [sample.get("id") for sample in samples] != expected_sample_ids:
    raise SystemExit("V2 M1-2 receipt/parser cap check: required sample inventory drifted")
for sample in samples:
    if not sample.get("generator") or not re.fullmatch(r"[0-9a-f]{64}", sample.get("rootSha256", "")):
        raise SystemExit("V2 M1-2 receipt/parser cap check: sample generator or root digest is missing")
registry_sample = next(sample for sample in samples if sample["id"] == "registry-readiness")
if registry_sample.get("bytesByKind", {}).get("REGISTRY_BYTES") != 51016:
    raise SystemExit("V2 M1-2 receipt/parser cap check: maximum Registry attachment is not exact")

expected_codes = [
    "RECEIPT_ROOT_NOT_REGULAR",
    "RECEIPT_ROOT_BYTES_EXCEEDED",
    "RECEIPT_MALFORMED_JSON",
    "RECEIPT_NON_CANONICAL_JSON",
    "RECEIPT_DUPLICATE_FIELD",
    "RECEIPT_UNKNOWN_OR_MISSING_FIELD",
    "RECEIPT_WRONG_TYPE_OR_NUMBER",
    "RECEIPT_SCHEMA_OR_KIND_INVALID",
    "RECEIPT_SOURCE_TUPLE_INVALID",
    "RECEIPT_SCENARIO_COUNT_EXCEEDED",
    "RECEIPT_SUITE_COUNT_EXCEEDED",
    "RECEIPT_ATTACHMENT_COUNT_EXCEEDED",
    "RECEIPT_DUPLICATE_OR_UNSORTED_ID",
    "RECEIPT_ACCOUNTING_INVALID",
    "RECEIPT_PATH_INVALID",
    "RECEIPT_PATH_BYTES_EXCEEDED",
    "RECEIPT_PATH_SEGMENTS_EXCEEDED",
    "RECEIPT_ATTACHMENT_BYTES_EXCEEDED",
    "RECEIPT_ATTACHMENT_TOTAL_BYTES_EXCEEDED",
    "RECEIPT_SANITIZED_LOG_BYTES_EXCEEDED",
    "RECEIPT_ATTACHMENT_NOT_REGULAR",
    "RECEIPT_ATTACHMENT_SYMLINK",
    "RECEIPT_ATTACHMENT_LENGTH_MISMATCH",
    "RECEIPT_ATTACHMENT_DIGEST_MISMATCH",
    "RECEIPT_CHECKED_ARITHMETIC_OVERFLOW",
    "RECEIPT_REQUIRED_SUITE_MISSING",
    "RECEIPT_MANDATORY_RESULT_NOT_PASS",
]
if evidence.get("rejectionCodes") != expected_codes:
    raise SystemExit("V2 M1-2 receipt/parser cap check: stable rejection taxonomy drifted")

test_evidence = evidence.get("testEvidence", {})
if test_evidence != {
    "expectedFocusedTests": 36,
    "expectedFailures": 0,
    "expectedErrors": 0,
    "expectedSkipped": 0,
    "dynamicTests": False,
    "internalRetries": False,
}:
    raise SystemExit("V2 M1-2 receipt/parser cap check: focused test contract drifted")

source_commit = source_commit_path.read_text(encoding="ascii").strip()
source_locks_input_sha = source_locks_input_path.read_text(encoding="ascii").strip()
if not re.fullmatch(r"[0-9a-f]{40}", source_commit):
    raise SystemExit("V2 M1-2 receipt/parser cap check: malformed source commit")
if not re.fullmatch(r"[0-9a-f]{64}", source_locks_input_sha):
    raise SystemExit("V2 M1-2 receipt/parser cap check: malformed source-lock input SHA")
expected_source = {
    "nereusCommit": source_commit,
    "requiredBaselineCommit": "7ede023e19774309268350a866932804787a52a7",
    "sourceLocksInputSha256": source_locks_input_sha,
}
if evidence.get("source") != expected_source:
    raise SystemExit("V2 M1-2 receipt/parser cap check: source tuple drifted")

subprocess.run(["git", "cat-file", "-e", f"{source_commit}^{{commit}}"], cwd=repo_root, check=True)
subprocess.run(
    ["git", "merge-base", "--is-ancestor", expected_source["requiredBaselineCommit"], source_commit],
    cwd=repo_root,
    check=True,
)
source_paths = [
    "build.gradle.kts",
    "scripts/check-v2-m1-receipt-caps.sh",
    "nereus-domain/src/test/java/com/nereusstream/domain/receipt/ReceiptV1CapacityModel.java",
    "nereus-domain/src/test/java/com/nereusstream/domain/receipt/ReceiptV1CapacitySamples.java",
    "nereus-domain/src/test/java/com/nereusstream/domain/receipt/ReceiptV1CapacityEvidenceTest.java",
    "nereus-domain/src/test/resources/receipt/m1-current-junit-inventory.tsv",
]
subprocess.run(["git", "diff", "--quiet", source_commit, "--", *source_paths], cwd=repo_root, check=True)
source_locks_at_source = subprocess.check_output(
    ["git", "show", f"{source_commit}:docs/v2/source-locks.json"], cwd=repo_root
)
if hashlib.sha256(source_locks_at_source).hexdigest() != source_locks_input_sha:
    raise SystemExit("V2 M1-2 receipt/parser cap check: source-lock input SHA differs from source commit")

for path in (model_path, samples_path):
    for imported in re.findall(r"^import ([^;]+);$", path.read_text(), flags=re.MULTILINE):
        if not (
            imported.startswith("java.")
            or imported.startswith("static java.")
            or imported.startswith("com.nereusstream.domain.receipt.ReceiptV1CapacityModel")
            or imported.startswith("static com.nereusstream.domain.receipt.ReceiptV1CapacityModel")
        ):
            raise SystemExit(f"V2 M1-2 receipt/parser cap check: non-JDK model dependency {imported}")

json_sha = hashlib.sha256(committed_json_bytes).hexdigest()
markdown = committed_markdown_path.read_text(encoding="utf-8")
if source_commit not in markdown or json_sha not in markdown:
    raise SystemExit("V2 M1-2 receipt/parser cap check: Markdown source or JSON digest binding drifted")

source_locks = json.loads(source_locks_path.read_text())
binding = source_locks.get("localImplementationEvidenceBindings", {}).get("m1.2ReceiptParserCaps")
expected_binding = {
    "nereusEvidenceCommit": source_commit,
    "sourceLocksInputSha256": source_locks_input_sha,
    "testArtifact": {
        "path": "docs/v2/evidence/v2-m0/m1-2-receipt-caps/receipt-caps.json",
        "bytes": len(committed_json_bytes),
        "sha256": json_sha,
    },
    "receipt": "docs/v2/evidence/v2-m0/m1-2-receipt-caps/README.md",
    "result": "RECEIPT_CAPACITY_READINESS_ONLY",
    "promotionEligible": False,
    "productionReceiptParserImplemented": False,
    "evidenceStatus": "READINESS_EVIDENCE",
}
if binding != expected_binding:
    raise SystemExit("V2 M1-2 receipt/parser cap check: source-lock evidence binding drifted")

scenario_data = json.loads(scenarios_path.read_text())
scenario_items = {item["id"]: item for item in scenario_data["scenarios"]}
if any(item.get("status") == "PASSED_CURRENT_SOURCE" for item in scenario_items.values()):
    raise SystemExit("V2 M1-2 receipt/parser cap check: scenario was promoted")
policy_readiness = scenario_items.get("V2-POLICY-001", {}).get("readinessEvidence")
if policy_readiness != {
    "path": "docs/v2/evidence/v2-m0/m1-2-receipt-caps/receipt-caps.json",
    "result": "RECEIPT_CAPACITY_READINESS_ONLY",
    "promotionEligible": False,
}:
    raise SystemExit("V2 M1-2 receipt/parser cap check: policy readiness binding drifted")

print(
    "V2 M1-2 receipt/parser caps: "
    f"suites=1 tests={totals['tests']} failures=0 errors=0 skipped=0 "
    f"jsonBytes={len(committed_json_bytes)} jsonSha256={json_sha}"
)
PY

echo "V2 M1-2 receipt/parser caps verified; no production parser, N1/N2/N3, scenario promotion, or M1 Final."
